# Generated by Django 3.0.2 on 2020-01-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[(0, 'ایرانی'), (1, 'فست\u200cفود'), (2, 'نوشیدنی'), (3, 'پیش\u200cغذا')], default=0, max_length=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurants')),
            ],
        ),
    ]
