# Generated by Django 3.0.2 on 2020-02-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200128_1747'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurants.Restaurants'),
        ),
    ]
