spring.application.name=demo
server.port=3000

spring.datasource.url=jdbc:mysql://localhost:3306/example
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
